timeout: '3600s'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'amd64'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/camera-http:amd64-$SHORT_SHA'
      - '-f'
      - './amd64.Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'arm32v7'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/camera-http:arm32v7-$SHORT_SHA'
      - '-f'
      - './arm32v7.Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'arm64v8'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/camera-http:arm64v8-$SHORT_SHA'
      - '-f'
      - './arm64v8.Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-amd64'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/camera-http:amd64-$SHORT_SHA'
    waitFor: ['amd64']


  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-arm32v7'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/camera-http:arm32v7-$SHORT_SHA'
    waitFor: ['arm32v7']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-arm64v8'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/camera-http:arm64v8-$SHORT_SHA'
    waitFor: ['arm64v8']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'manifest'
    env:
      - 'DOCKER_CLI_EXPERIMENTAL=enabled'
    args:
      - 'manifest'
      - 'create'
      - 'gcr.io/$PROJECT_ID/camera-http:latest-$BRANCH_NAME'
      - 'gcr.io/$PROJECT_ID/camera-http:amd64-$SHORT_SHA'
      - 'gcr.io/$PROJECT_ID/camera-http:arm32v7-$SHORT_SHA'
      - 'gcr.io/$PROJECT_ID/camera-http:arm64v8-$SHORT_SHA'
    waitFor: ['push-amd64', 'push-arm32v7', 'push-arm64v8']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'annotate-manifest-amd64'
    env:
      - 'DOCKER_CLI_EXPERIMENTAL=enabled'
    args:
      - 'manifest'
      - 'annotate'
      - 'gcr.io/$PROJECT_ID/camera-http:latest-$BRANCH_NAME'
      - 'gcr.io/$PROJECT_ID/camera-http:amd64-$SHORT_SHA'
      - '--os=linux'
    waitFor: ['manifest']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'annotate-manifest-arm32v7'
    env:
      - 'DOCKER_CLI_EXPERIMENTAL=enabled'
    args:
      - 'manifest'
      - 'annotate'
      - 'gcr.io/$PROJECT_ID/camera-http:latest-$BRANCH_NAME'
      - 'gcr.io/$PROJECT_ID/camera-http:arm32v7-$SHORT_SHA'
      - '--os=linux'
      - '--arch=arm'
      - '--variant=v7'
    waitFor: ['manifest']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'annotate-manifest-arm64v8'
    env:
      - 'DOCKER_CLI_EXPERIMENTAL=enabled'
    args:
      - 'manifest'
      - 'annotate'
      - 'gcr.io/$PROJECT_ID/camera-http:latest-$BRANCH_NAME'
      - 'gcr.io/$PROJECT_ID/camera-http:arm64v8-$SHORT_SHA'
      - '--os=linux'
      - '--arch=arm64'
      - '--variant=v8'
    waitFor: ['manifest']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-manifest'
    env:
      - 'DOCKER_CLI_EXPERIMENTAL=enabled'
    args:
      - 'manifest'
      - 'push'
      - 'gcr.io/$PROJECT_ID/camera-http:latest-$BRANCH_NAME'
    waitFor: ['annotate-manifest-amd64', 'annotate-manifest-arm32v7', 'annotate-manifest-arm64v8']
