apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camera
  template:
    metadata:
      labels:
        app: camera
    spec:
      containers:
        - name: camera
          image: gcr.io/teknoir/camera-http:latest-master
          imagePullPolicy: IfNotPresent
          env:
            - name: MQTT_SERVICE_HOST
              value: "mqtt.kube-system"
            - name: MQTT_SERVICE_PORT
              value: "1883"
            - name: MQTT_OUT_0
              value: "camera/images"
            - name: UPDATE_INTERVAL
              value: "5000"
            - name: BASE_URL
              value: "http://192.168.0.186/snap.jpg?JpegSize=L"
            - name: AUTH_TYPE
              value: "digest"
            - name: USERNAME
              value: "service"
            - name: PASSWORD
              value: "Teknoir202!"
