site_name: HTTP Camera App User documentation
site_description: The camera app collect images from cameras over http/api.
repo_url: https://github.com/teknoir/camera-http
edit_uri: edit/main/docs

nav:
  - Start: 'index.md'

plugins:
  - techdocs-core
